parameters:

    gearman.client.class:           Mmoreram\GearmanBundle\Service\GearmanClient
    gearman.execute.class:          Mmoreram\GearmanBundle\Service\GearmanExecute
    gearman.describer.class:        Mmoreram\GearmanBundle\Service\GearmanDescriber
    gearman.cache.wrapper.class:    Mmoreram\GearmanBundle\Service\GearmanCacheWrapper
    gearman.cache.id:               gearman.workers