parameters:
    config.path:                /config/Gearman/
  
    gearman.class:              Mmoreramerino\GearmanBundle\Service\Gearman
    gearman.cache.class:        Mmoreramerino\GearmanBundle\Service\GearmanCache
    gearman.execute.job.class:  Mmoreramerino\GearmanBundle\Service\GearmanExecute
    gearman.settings.class:     Mmoreramerino\GearmanBundle\Service\GearmanSettings
services:
    gearman: 
        class: %gearman.class%
        calls:
          - [setContainer,  [@service_container]]
    gearman.settings: 
        class: %gearman.settings.class%
        calls:
          - [setContainer,  [@service_container]]
          - [loadSettings,  []]
    gearman.cache: 
        class: %gearman.cache.class%
        calls:
          - [setContainer,  [@service_container]]
          - [loadCache,  []]
    gearman.execute.job: 
        class: %gearman.execute.job.class%
        calls:
          - [setContainer,  [@service_container]]