services:

    gearman.cache.wrapper:
        class: %gearman.cache.wrapper.class%
        arguments:
            kernel: @kernel
            gearman.cache: @liip_doctrine_cache.ns.gearman
            gearman.cache.id: %gearman.cache.id%
            gearman.bundles: %gearman.bundles%
            gearman.servers: %gearman.servers%
            gearman.default.settings: %gearman.default.settings%
        calls:
            - [loadNamespaceMap,  []]
            - [load,  []]
        tags:
            - { name: kernel.cache_clearer }
            - { name: kernel.cache_warmer, priority: 0 }

    gearman.describer:
        class: %gearman.describer.class%
        arguments:
            kernel: @kernel

    gearman.callbacks:
        class: %gearman.callbacks.class%
        arguments:
            event.dispatcher: @event_dispatcher

    gearman.abstract.service:
        abstract:  true
        arguments:
            gearman.cache.wrapper: @gearman.cache.wrapper
            default_settings: %gearman.default.settings%

    gearman.execute:
        class: %gearman.execute.class%
        parent: gearman.abstract.service
        calls:
            - [setContainer,  [@service_container]]

    gearman:
        class: %gearman.client.class%
        parent: gearman.abstract.service
        calls:
            - [setDefaultServers, [%gearman.servers%]]
            - [setGearmanCallbacks, [@gearman.callbacks]]
            - [setDefaultSettings, [%gearman.default.settings%]]