parameters:
    gearman.config.path:        %kernel.root_dir%/config/gearman/%kernel.environment%.yml

    gearman.client.class:       Mmoreram\GearmanBundle\Service\GearmanClient
    gearman.cache.class:        Mmoreram\GearmanBundle\Service\GearmanCache
    gearman.cache.loader.class: Mmoreram\GearmanBundle\Service\GearmanCacheLoader
    gearman.execute.class:  Mmoreram\GearmanBundle\Service\GearmanExecute
    gearman.settings.class:     Mmoreram\GearmanBundle\Service\GearmanSettings
    gearman.describer.class:     Mmoreram\GearmanBundle\Service\GearmanDescriber
services:
    gearman:
        class: %gearman.client.class%
        calls:
          - [setContainer,  [@service_container]]
    gearman.settings:
        class: %gearman.settings.class%
        calls:
          - [setContainer,  [@service_container]]
          - [loadSettings,  []]
    gearman.cache:
        class: %gearman.cache.class%
        calls:
          - [setContainer,  [@service_container]]
          - [loadCache,  []]
    gearman.cache.loader:
        class: %gearman.cache.loader.class%
        calls:
          - [setContainer,  [@service_container]]
    gearman.execute:
        class: %gearman.execute.class%
        calls:
          - [setContainer,  [@service_container]]
    gearman.describer:
        class: %gearman.describer.class%
        calls:
          - [setContainer,  [@service_container]]