parameters:
    gearman.config.path:        %kernel.root_dir%/config/gearman/%kernel.environment%.yml

    gearman.client.class:       Mmoreram\GearmanBundle\Service\GearmanClient
    gearman.cache.id:           gearman.workers
    gearman.cache.wrapper.class: Mmoreram\GearmanBundle\Service\GearmanCacheLoader
    gearman.execute.class:  Mmoreram\GearmanBundle\Service\GearmanExecute
    gearman.settings.class:     Mmoreram\GearmanBundle\Service\GearmanSettings
    gearman.describer.class:     Mmoreram\GearmanBundle\Service\GearmanDescriber



services:
    gearman:
        class: %gearman.client.class%

    gearman.cache.wrapper:
        class: %gearman.cache.wrapper.class%
        arguments:
            gearman.bundles: %gearman.bundles%
            kernel: @kernel
            gearman.cache: @liip_doctrine_cache.ns.mmoreram_gearman
            gearman.cache.id: %gearman.cache.id%
        calls:
          - [loadNamespacesMap,  []]

    gearman.execute:
        class: %gearman.execute.class%
        calls:
          - [setContainer,  [@service.container]]

    gearman.describer:
        class: %gearman.describer.class%
        arguments:
            kernel: @kernel